conky.config = {
    alignment = 'top_middle',
    background = true,
    border_width = 1,
    cpu_avg_samples = 2,
    default_color = 'white',
    default_outline_color = 'white',
    default_shade_color = 'white',
    double_buffer = true,
    draw_borders = false,
    draw_graph_borders = true,
    draw_outline = false,
    draw_shades = false,
    extra_newline = false,
    font = 'DejaVu Sans Mono:size=30', -- Lettertype vergroot naar 14
    gap_x = 40,
    gap_y = 60,
    minimum_height = 1000,
    minimum_width = 650, -- Venster breder gemaakt voor betere leesbaarheid
    net_avg_samples = 2,
    no_buffers = true,
    out_to_console = false,
    out_to_ncurses = false,
    out_to_stderr = false,
    out_to_x = true,
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'desktop',
    own_window_transparent = true,
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    show_graph_range = false,
    show_graph_scale = false,
    stippled_borders = 0,
    update_interval = 2.0,
    uppercase = false,
    use_spacer = 'none',
    use_xft = true,
    color1 = '00FF00', -- Groen voor ONLINE
    color2 = 'FF0000', -- Rood voor OFFLINE
    color3 = '3399FF', -- Blauw voor titels
}

conky.text = [[

${if_existing /dev/shm/meteo.png}${image /dev/shm/meteo.png -p 10,600 -s 650x380 -n}${endif}

]]

